# Define the task
string id
ConstraintSpec[] primary
ConstraintSpec[] auxiliary
ConstraintSpec[] safety
MonitorSpec[] monitors
---
# Define the result
bool res
---
# Define a feedback message
string[] events
ContinuousFeedback feedback